# Site settings
title: GAMENAO
email: 
description: A simple blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: notmackintosh
github_username:  mackintosh
exclude: ['deploy']

# Build settings
markdown: kramdown
